version: '3'
services:
  app:
    container_name: react-blackjack
    image: node:16.14.2-alpine
    working_dir: /app
    build: .
    volumes:
      - ./:/app
    command: sh -c 'npm install && npm start'
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
